=== PedroRuiz/interlingua/assets/xml/document.dtd
<!-- una DTD para documento de Interlingua -->
<!ELEMENT documento (typo,designo?,data,incatenar?,taxinomia,autores,contento*) >
    
    <!ELEMENT typo              (#PCDATA)>                      <!-- declaration del typo de documento p.i.: traducction,information,linguistic, etc. -->
    
	<!ELEMENT designo           (#PCDATA)>                      <!-- schema de pagina, per defecto 'pages' -->
	
    <!ELEMENT data              (#PCDATA)>                      <!-- data expresate como aaaa-mm-dd -->
    
    <!ELEMENT incatenar         (vade*,veni*)?>                 <!-- OPTATIVE declarate solmente si iste documento on incatena con alteres -->
        <!ELEMENT vade          (#PCDATA)>                      <!-- documento al que vade -->
        <!ELEMENT veni          (#PCDATA)>                      <!-- documento del que veni -->
    
    <!ELEMENT taxinomia         (#PCDATA)>                      <!-- un description del contento del documento -->
    
    <!ELEMENT autores           (autor?)*>                      <!-- OPTATIVE autores (NO ON POTE REPETER)-->
        <!ELEMENT autor	        (nomine,retes*)>                 <!-- cata un del autores -->
            <!ELEMENT nomine 		(#PCDATA)>                  <!-- nomine del autor -->
            <!ELEMENT retes 		(#PCDATA)>                  <!-- un per cata retes social del autor ON POTE REPETER, p.i. email, twitter, facebook, etc -->
    
    <!ELEMENT contento          (titulo,imagine,texto*)>  <!-- declaration del contento (NO ON POTE REPETER) -->
		<!ELEMENT menu			(menunomine,menudata)*>
			
        <!ELEMENT titulo        (#PCDATA)>                      <!-- titulo (NO ON POTE REPETER)-->
        <!ELEMENT imagine       (#PCDATA)>                      <!-- imagine (NO ON POTE REPETER)-->
		<!ELEMENT texto       (#PCDATA)>                      
<![IGNORE[	
		<!ELEMENT texto 		(#PCDATA|nigre|cursiva|centrar|textitulo|teximagine|parve|ligamine)*>
			<!ELEMENT nigre		 	(#PCDATA)> 		
    		<!ELEMENT cursiva	 	(#PCDATA)>
    		<!ELEMENT centrar		(#PCDATA)>
			<!ELEMENT textitulo		(#PCDATA)>
			<!ELEMENT teximagine	(#PCDATA)>    	
			<!ELEMENT parve			(#PCDATA)>	
			<!ELEMENT ligamine		(direction,textoligamine)>
				<!ELEMENT direction		(#PCDATA)>
				<!ELEMENT textoligamine	(#PCDATA)>
]]>

=== PedroRuiz/interlingua/assets/xml/pages/le_violentia_es_un_crimine.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE documento SYSTEM "../document.dtd">
<documento>
    <typo>Traductiones</typo>
    <data>20180115</data>
    <incatenar>
        <veni>https://interlingua.pedroruizhidalgo.es/leger</veni>
    </incatenar>
    <taxinomia>Le violentia es un crimine</taxinomia>
    <autores>
        <autor>
            <nomine>Carmelo Serraino</nomine>
            <retes>melo serraino</retes>
        </autor>
    </autores>
    <contento>
        <titulo>Le violentia es un crimine. Ma la corte insistente o inhabile non es un delicto, ni le galanteria
amorose es un aggression machiste.</titulo>
        <imagine>https://interlingua.pedroruizhidalgo.es/assets/image/Deneuve.jpg</imagine>
        <texto>/boldDepost le affaire Weinstein ha habite loco un justificate prisa de conscientia del violentias sexual exercite sur le feminas, particularmente in le quadro professional, ubi alcunes abusava de lor poter. Illo era necessari. Ma iste liberation del parola se retorna hodie in su contrario: on nos intima de parlar como il conveni, de tacer lo que  de irate, e illas que refusa de se plicar a tal injunctiones son reguardate como traitrices, complices!bold/

Ora es justo le characteristica del puritanismo facer se prestar, a nomine de un pretendite ben general, le argumentos del protection del feminas e de lor emancipation pro melio las attachar con un catena a un stato juridic de eterne victimas, paupere parve cosas sub le ascendente de demones phallocrate, como al bon vetere tempore del magia.

/em/boldDelationes e posas in stato de accusationbold/em/

De facto, #metoo a trainate in le pressa e sur le retes social un campania de delationes e de posas in accusation public de individuos qui, sin que on lor lassa la possibilitate ni de responder ni de se defender, ha essite mittite exactemente sur le mesme plano del aggressores sexual. Iste justitia expeditive ha jam su victimas, homines sanctionate al exercitio de lor mestiero, obligate al dimission, et cetera, quando illes non ha habite que le sol torto de haber toccate un genu, tentate de furar un basio, parlate de cosas «intime» al tempore de un prandio professional o de haber inviate del messages a connotation sexual a un femina cuje le attraction non era reciproc.

Iste febre a expedir le «porcos» al abattitorio, distante de adjutar le feminas a se render autonome, servi in realitate le interesses del inimicos del libertate sexual, del extremistas religiose, del pejor reactionarios e de illes qui estima, in nomine de un conception substantial del ben e del moral victorian que va insimul a que: le feminas son del individuos «a parte», infantes a visage de adulte, personas reclamante de esser protegite.

Per contra, le homines son vocate a confessar lor culpa e a revelar, in fundo a lor conscientia retrospective, un «comportamento inappropriate» que illes haberea potite haber dece, vinti o trenta annos retro, e de cuje illes deberea repentir se. La confession public, le incursion de auto-proclamate procuratores in le sphera private, ecce que installa como un climate de societate totalitari.

Le unda purificator non pare cognoscer alcun limite. Ibi, on censura un nudo de Egon Schiele sur un affiche; ci, on appella al retiro de un pictura de Balthus ab un museo, per motivo que il esserea un apologia del pedophilia; in le confusion del homine e del obra, on demanda le interdiction del retrospectiva de Roman Polanski al cinematheca e on obtene le prolongation de illo consecrate a Jean-Claude Brisseau. Un universitario judica le film Blow-Up, de Michelangelo Antonioni, «misogyne» e «inacceptabile». Al luce de iste revisionismo, John Ford (La Prisonnière du désert) e mesmo Nicolas Poussin (L’Enlèvement des Sabines) non duce al largo.

Jam, alcun editores demanda a certes de nos de render nos personages masculin minus «sexista», de parlar de sexualitate e de amor con minus dismesura o ancora de facer in modo que le «traumatismos subite per le personages feminin» sia rendite plus evidente! Al margine del ridiculo, un projecto de lege in Svedia vole imponer un consentimento explicitemente notificate a tote le candidates a un reporto sexual! Ancora un effortio e duo adultes qui habera desiderio de se mitter a lecto insimul debera previemente marcar de unsigno, via un «application» de lor telephono, un documento in le qual le practicas que illes accepta e los que illes refusa sera debitemente listate.

/em/boldLe indispensabile libertate de offender bold/em/

Le philosopho Ruwen Ogien defendeva un libertate de offender indispensabile al creation artistic. Mesmo, nos defende un libertate de importunar, indispensabile al libertate sexual. Nos es hodie sufficientemente avertite pro admitter que la pulsion sexual es per natura offensive e salvage, ma nos es anque sufficientemente clarividente pro non confunder le corte inhabile e le aggression sexual.

Ante toto, nos es consciente que la persona human non es monolithic: un femina pote, in le mesme jornata, diriger un equipa professional e gauder de esser le objecto sexual de un homine, sin esser un «canalia», ni un vil complice del patriarchato. Illa pote veliar a fin que su salario sia equal a illo de un homine, ma non se sentir traumatisate a jammais affrontar un fricator in le metro, mesme si illo es considerate como un delicto. Illa pote mesmo lo considerar como le expression de un grande miseria sexual, vider como un
non-evenimento.

In tanto que feminas, nos non recognosce nos in iste feminismo qui, alteremente del denunciation del abuso de poter, prende le connotationes de un odio del homines e del sexualitate. Nos pensa que la libertate de dicer no a un proposition sexual non existe sin la libertate de importunar. E nos considera que il es necesse saper responder a iste libertate de importunar sin se clauder al rolo de preda. 

Pro illas de nos qui ha eligite de haber infantes, nos estima que il es plus judiciose de elevar nos filios de maniera que illes son sufficientemente informate e consciente pro poter viver plenmente lor vita sin se lassar intimidar, ni patir un sentimento de culpabilitate.

Le accidentes que pote concerner le corpores de un femina non attinge necessarimente su dignitate e non debe, mesmo si isto pote ser a vices dur, necessarimente facer de illa un victima perpetue. Proque nos non es reducibile a nostre corpores. Nostre libertate interior es inviolabile. E iste libertate que nos ama non es sin riscos, ni sin responsabilitates.

Les redactrices de ce texto son: Sarah Avar (scriptrice, psychologo clinic e psychoanalysta), Catharina Milio (critic de arte, scriptrice), Catharina Robbe-Grillet (actrice de comedia e scriptrice), Peggy Sastre (autor, jornalista e traductrice), Abnousse Shalmani (scriptrice e jornalista). Adhere equalmente a iste tribuna: Kathy Alliou (curatrice), Marie-Laure Bernadac (conservator general honorari), Stéphanie Blake (autor de libros pro infantes), Ingrid Caven (actrice e cantatrice), Catharina Deneuve (actrice), Gloria Friedmann (artista plastic), Cécile Guilbert (autor), Brigitte Jaques-Wajeman (director de scena), Claudine Junien (geneticista), Brigitte Lahaie (actrice e presentatrice radio), Nathalie Legier (scriptrice e directrice general del Institut mémoires de l’édition contemporaine), Elisabeth Lévy (directrice del redaction de Causeur), Joëlle Losfeld (editrice), Sophie de Menthon (presidente del movimento ETHIC), Maria Sellero (autor, presidente del Société des gens de lettres).

/boldFonte: Le Monde. Fonte: www.kassataya.combold/

Traducite a interlingua per /boldCarmelo Serrainobold/ 13 jan. 2018</texto>
    </contento>
</documento>

=== PedroRuiz/interlingua/assets/xml/pages/platero_2.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE documento SYSTEM "../document.dtd">
<documento>
    <typo>Traductiones</typo>
    <data>20180104</data>
    <incatenar>
        <vade>http://interlingua.pedroruizhidalgo.es/documento/platero_3</vade>
        <veni>http://interlingua.pedroruizhidalgo.es/documento/platero_1</veni>
    </incatenar>
    <taxinomia>Paisage rubie</taxinomia>
    <autores>
        <autor>
            <nomine>Pedro Ruiz Hidalgo</nomine>
            <retes>@pedroruizhidalg</retes>
            <retes>interlingua@pedroruizhidalgo.es</retes>
        </autor>
    </autores>
    <contento>
        <titulo>Platero e io</titulo>
        <imagine>https://interlingua.pedroruizhidalgo.es/assets/image/platero_2.jpg</imagine>
        <texto>Le culmine. Ibi es le poner del sol, tote purpuree, ferite pro su proprie crystallos, que face le sanguine por ubicunque. A su splendor, le pineto verde on face acerbe, vagemente rubifacite; e le herba e le floretto, incendite e transparente, imbalsama le instante seren de un essentia molliate, penetrante e luminose.</texto>
        <texto>Io permane ecstasiate in le crepusculo. Platero, rubie de poner del sol su oculos nigre, on va, mansuete, a un cavo de aqua carminee, de rosa, de violetto; affunda suavemente su bucca in le speculos, que pare que on face liquide al toccar lo ille; e ha pro su enorme gorga como un passar profuse umbrose aquas de sanguine.</texto>
        <texto>Le localitate es cognoscite, sed le momento disordina lo e lo face estranio, ruinose e monumental. On dicerea, a cata instante, que nos va a discoperir un palatio abandonate... Le postmeridie on prolonga plus illac de illa mesme, e al hore, contagiate de eternitate, es infinite; pacific, insondabile...</texto>
        <texto>â€”Cammina Platero...</texto>
    </contento>
</documento>

=== PedroRuiz/interlingua/assets/xml/pages/mandala_1.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE documento SYSTEM "../document.dtd">
<documento>
    <typo>Romanica</typo>
    <data>20180115</data>
    <incatenar>
        <vade>https://interlingua.pedroruizhidalgo.es/documento/mandala_2</vade>
        <veni>https://interlingua.pedroruizhidalgo.es/leger</veni>
    </incatenar>
    <taxinomia>Orientar se con una mappa mental</taxinomia>
    <autores>
        <autor>
            <nomine>Herminio Latone</nomine>
            <retes> Vivacchiananda</retes>
        </autor>
    </autores>
    <contento>
        <titulo>COGNOSCER LO BUDDHISMO A PARTIR DE UN DIAGRAMMA</titulo>
        <imagine>https://interlingua.pedroruizhidalgo.es/assets/image/mandala1.jpg</imagine>
        <texto>Observamos ista pictura o mandala, etiam si mandala est solmente uno appello conventional, initiamos a vider lo como un designo o una mappa, proque de illo se tracta.
        Considerando alora iste diagramma como una mappa, la prima cosa a facer est comprehender cello que son los symbolos, ni plus ne minus como se facet con una clave al pede della pagina.

Le panorama non est celestial, illo est simplicemente un panorama terrestrial, typic dellos locos de ubi provenet (Tibet), ce son etiam le sol e la luna a demonstrar le caracter mondan, toto isto stat a significar que istas cosas son humanas.

Nelle portion superior il han tres figuras, illas stan a significar uno concepto fundamental, le transformation delle mente, della parola et dello acto.

/titLe mente sta nello medio.tit/
Desde une mente ben controllate et developpate il haberan parolas et actos qui apportaran beneficios alle hommine sage et alles hommines proximes a ille.

Los beneficios seran in ista existentia proque solmente dum ista vita nos potemos contolar le nostre mente.

Complir un percurso de tranformation (in melio), secundo lo buddhismo, non est un action passive e por obtener dellos resultatos se debet laborar, mesmo alle labor ordinari que, si facite ben, apportarat gaino monetari.

Por facer lo ben on debet apprehender uno methodo, uno methodo lo qual ha essito projectato como apto allo objectivo  e sullo qual, solmente le «laborator» potet dicer la ultima parola.

Le recercator, alsi, trovarat plures methodos dum les sues investigationes, proque lo concepto de base est applicabile a plures formas explicativas.

Lo objectivo est aquello de mutar los pensamentos negativos in pensamentos positivos, inde reducer o eliminar las parolas e los actos negativos.

Isto conduce a un melior relation inter nos e lo universo qui ce imbraciat e le elimination de multes sufferentias delles quales nos mesmos essemos la causa.

Le comprehension de isto mechanismo est communemente appellato eveliamento e lo suo plus alto scopo est le liberation delle hommine desde las sufferentias, o plus correctemente, desde les sues afflictiones.

Les personages colorates de isto mandala non son divinitate, illes son «statos» mentales delles hommines, cata una est uno stato mental e lo suo opposito in se mesmo, aquello sin controllo e aquello controllato qui co-existen.

Antea de vader a explicar las sequentes figurettas il hat a dicer que, como se potet haber una mappa desegnata, on potet haber etiam una mappa «parlata» quando il hat le necessitate a rememorar los conceptos qui videremos.

Facer lo est multo simplice, se associat cata una figura/concepto con una paroletta conventional, isto systema que non habet nihil de mysterioso o magico est appellato mantra, un mantra non est un invocation ot un oration, illo est, como dicito, una mappa parlante.

Allas figuras de ja explicatas se associan istas parolettas:
/center /em Om     (le mente)
      Ah       ( la parola) 
    Hum     (lo acto)  em/ center/
Facite iste introduction, /boldvamos a vider las figurettas plus grandasbold/.</texto>
        
    </contento>
</documento>

=== PedroRuiz/interlingua/assets/xml/pages/protocollos_0.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE documento SYSTEM "../document.dtd">
<documento>
    <typo>Traductiones</typo>
    <data>20180115</data>
    <incatenar>
        <vade>https://interlingua.pedroruizhidalgo.es/documento/protocollos_1</vade>
        <veni>http://interlingua.pedroruizhidalgo.es/leger</veni>
    </incatenar>
    <taxinomia>Sages de Sion, Introduction</taxinomia>
    <autores>
        <autor>
            <nomine>Pedro Ruiz Hidalgo</nomine>
            <retes>@pedroruizhidalg</retes>
        </autor>
    </autores>
    <contento>
        <titulo>Protocollos del 
sages de Sion: Introduction</titulo>
        <imagine>https://interlingua.pedroruizhidalgo.es/assets/image/sages.jpg</imagine>
        <texto>Protocollos del sages de Sion es un documento fundamental que pone in evidentia le plan de domination mundial pro parte del Judeos. Habeva numerose debattos re le origine de iste documento. Varie expertes concorda in que esseva create in 1897, in le prime congresso sionista celebrate in Basel. Altere affirma que ha essite create  in un session secrete de sages judee que habeva essite effectuate in iste epocha. Le presse judee ha dismentite ista veritate usque ridiculisar le. Il es in nos, esser infidel al legato que illes nos lassava le expertes in le thema. Non es question de creder cecamente, nec vider e corroborar que la intention del sionismo pro dominar le mundo on repete in tote le epochas e in omne paises del mundo. Protocollos del sages de Sion es dividite in 24 partes o protocollos. Ille parla re ipse mesme. Il es multo importante cognoscer le significato del alicunos terminos usate in este documento:

/boldGoimbold/: (singular: Goy) Parola hebree usate in forma despectose pro referer se al non gentil (non judee) e que significa bestial.
Sionismo / Sionisme: Movimento mundial pro le avantiar e custodia del interesses politic-economic del judeos.

/boldGentilbold/: Vider Goim.

/boldMasoneriabold/: Actualmente es societates secrete que travalia misteriosemente in le umbra, empleante omne classe de artifices subterranee. In lor major parte iste organisationes es integrate pro le judee, tanto in le cupula como in lor differente hierarchias o grados .

/boldFrancmasoneriabold/: Organisation aristocratica intra del masoneria, le qual es ric e poterose. Il es protegite pro le soveran, cuje membros es admittite in le corporation post un initiation, sequite de provas moral e physica. Iste secta ha le discretional de eliminar secrete o publicamente a qui non considera apte.</texto>
    </contento>
</documento>

=== PedroRuiz/interlingua/assets/xml/pages/platero_3.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE documento SYSTEM "../document.dtd">
<documento>
    <typo>Traductiones</typo>
    <data>20180105</data>
    <incatenar>
        <vade>http://interlingua.pedroruizhidalgo.es/documento/platero_4</vade>
        <veni>http://interlingua.pedroruizhidalgo.es/documento/platero_2</veni>
    </incatenar>
    <taxinomia>Gaudio</taxinomia>
    <autores>
        <autor>
            <nomine>Pedro Ruiz Hidalgo</nomine>
            <retes>@pedroruizhidalg</retes>
            <retes>interlingua@pedroruizhidalgo.es</retes>
        </autor>
    </autores>
    <contento>
        <titulo>Platero e io</titulo>
        <imagine>https://interlingua.pedroruizhidalgo.es/assets/image/platero_3.jpg</imagine>
        <texto>Platero joca con Diana, le belle can feminin que on pare al luna crescente, con le vetule capra, gris, con los infantes...

Salta Diana, agile e elegante, ante le asino, sonante su breve campanetto, e face como que le morde su muso. E Platero, ponente le aures alte, qual duo cornos de cacto, ille hasta le blandemente, e face la rodar super le herba en flor.

Le capra vade al latere de Platero, racente a su gambas, trahente, con su dentes, del puncta del stoffa del carga. Con un floretto o un margarita en le bucca, on pone ante el, le chocca con le fronte, e depost salta, e bala gaudiosemente, caressabile eque un femina...

Inter le infantes, Platero esse un joculo. Con que patientia suffre lor follias! Como vade lentemente, stoppante se, on face el orate, pro que illos non cade! Como los espaventa quando initia, subitemente, un false trottar!
â€¦...........................

Clar postmeridie del autumno moguerese1! Quando le aere pur de octobre affila le immaculate sonos, on altia del valle un agitation idyllic de balamentos, hinnimentos, de risos de infantes, latratos, e campanettas</texto>
        
    </contento>
</documento>

=== PedroRuiz/interlingua/assets/xml/pages/dust_in_the_wind.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE documento SYSTEM "../document.dtd">
<documento>
    <typo>Traductiones</typo>
    <data>20180116</data>
    <incatenar>
        <veni>https://interlingua.pedroruizhidalgo.es/leger</veni>
    </incatenar>
    <taxinomia>Dust in the wind</taxinomia>
    <autores>
        <autor>
            <nomine>Pedro Ruiz Hidalgo</nomine>
            <retes>interlingua@pedroruizhidalgo.es</retes>
            <retes>@pedroruizhidalg</retes>
        </autor>
    </autores>
    <contento>
        <titulo>Pulvere in le vento</titulo>
        <imagine>https://interlingua.pedroruizhidalgo.es/assets/image/dust_in_the_wind.jpg</imagine>
        <texto>Io claude le oculos
sol per un momento
e le momento passa.

Tote mi somnos
passa fronte de mie oculos:
un curiositate.

/bold/emPulvere in le vento,
omne que nos esse, es pulvere in le vento.em/ bold/

Como en un vetule canto,
sol un gutta de aqua
en un mar immense.

Le mesme vetule canto,
sol un gutta de aqua
en un immense mar.
Omne que nos face,
on cade,
benque no no vole vider lo.

/bold/emPulvere in le vento,
omne que nos esse, es pulvere in le vento.em/ bold/

Que tu non resiste,
nihil es per sempre,
ma le Terra e le celo.
Il on escappa 
omne tu pecunia
non pote comprar un minuto.

/bold/emPulvere in le vento,
omne que nos esse, es pulvere in le vento.em/ bold/
/bold/emPulvere in le vento,
omne que nos esse, es pulvere in le vento.em/ bold/

/link"https://www.youtube.com/watch?v=2-I-BhaiTzw"/l_Audi "Dust in the wind" in Youtubel_/ link/

</texto>
        <texto>/img"https://interlingua.pedroruizhidalgo.es/assets/image/kansas.jpg"img/
            /smallFonte poesia: /boldKansas.bold/ small/</texto>
    </contento>
</documento>

=== PedroRuiz/interlingua/assets/xml/pages/forsan_un_conto.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE documento SYSTEM "../document.dtd">
<documento>
    <typo>Scriptes de autor</typo>
    <data>20180116</data>
    <incatenar>
        <veni>https://interlingua.pedroruizhidalgo.es/leger</veni>
    </incatenar>
    <taxinomia>Un conto, forsan...</taxinomia>
    <autores>
        <autor>
            <nomine>Pedro Ruiz Hidalgo</nomine>
            <retes>interlingua@pedroruizhidalgo.es</retes>
            <retes>@pedroruizhidalg</retes>
        </autor>
    </autores>
    <contento>
        <titulo>Tango</titulo>
        <imagine>https://interlingua.pedroruizhidalgo.es/assets/image/tango2.jpg</imagine>
        <texto>Un besonio de adventura, forsan producite pro mi habitual solitude acquirite durante annos, produce in me un specie de sentimento que io non es capace de nominar. Quando iste sentimento explode, io va deambular pro obscur stratas, cercante un maniera de plenar iste momento con un responsa como in le natura on completa de vita, io necessita in mi interior un explosion de sensationes que appacia al monstro vacue. Qui sole star sol, on habitua a observar circum, e imagina lo que es reguardate inter cerebro e corde, a equal partes.

Jam exhauste de retener imagines e mementos como souvenirs intra me, ego audiva le lontan e languide musica de un tango. Illo esseva musicate con un aira, plus que triste, azur, un azur dense e attrahente, un audio con tante densitate que il pare que exercita su gravitation super me, que me attrahe, assi, annulate mi voluntate, io non pote facer altere cosa que entrar in le lugubre e mysteriose local.

Pulvere, sudor miscite con odor a tabaco nigre, in un ambiente que parerea vetule in le annos cinquanta, illo era un schola de tango. Retro un barra de bar con plus aira de ser cuban que argentin. Un grasse e immense servitor con un pesate camminar saluta con un essayate gesto de capite. 

―Que desira vos? ―Demanda me con un gesto de dolor in su facie que symmetricamente representa su camminar. 
―Rum con gelo.

Bebe io duo curte sorbe, e observa que on approxima un femina ridente. Face un gesto de tango al aira, sue gambas, coxal, e bracios on move in un gesto de invitation a ballar. Invitation que, pro le effecto del gravitate, del sudor, del accordion, o de mi solitude io tende mi mano sin surrider, sed, ego accepta in un universo de tabaco nigre e tango. Le brun e belle dama pone mi mano super su spatula dextere durante que illa balla, approxima nos al centro del pista de ballar. Non pote io lassar de reguardar su colossal coxal que, plus illac de mover se al rhythmo de tango, realmente on move al rhythmo de mi desiros.

―Qual es tu nomine? ―Demanda quando monstra su carnose e rubie labios.
―Paco. ―Menti ego quando in un rapide gesto stiva mi anello in mi tasca del pantalones.
/smallAutor del conto:Pedro Ruiz Hidalgo.small/

</texto>
        <texto>/img"https://interlingua.pedroruizhidalgo.es/assets/image/tango.png"img/</texto>
    </contento>
</documento>

=== PedroRuiz/interlingua/assets/xml/pages/platero_6.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE documento SYSTEM "../document.dtd">
<documento>
    <typo>Traductiones</typo>
    <data>20180106</data>
    <incatenar>
        <vade>http://interlingua.pedroruizhidalgo.es/documento/platero_7</vade>
        <veni>http://interlingua.pedroruizhidalgo.es/documento/platero_5</veni>
    </incatenar>
    <taxinomia>ANGELUS!</taxinomia>
    <autores>
        <autor>
            <nomine>Pedro Ruiz Hidalgo</nomine>
            <retes>@pedroruizhidalg</retes>
            <retes>interlingua@pedroruizhidalgo.es</retes>
        </autor>
    </autores>
    <contento>
        <titulo>Platero e io</titulo>
        <imagine>https://interlingua.pedroruizhidalgo.es/assets/image/platero_6.jpg</imagine>
        <texto>Reguarda, Platero, quante rosas cade pro tote locos: rosas blau, rosas blanc, sin color... On poterea dicer que le celo disface se in rosas. Vide como on plena me de rosas le fronte, le spatulas, le manos... Que facera io con tante rosas?

Tu sape, forsan, de ubi es iste blande flora, que io no sape de ubi es, que molli, cata die, le paisage e lassa lo dulcemente rosate, blanc e celeste—, plus roses, plus roses—, como un quadro de Fra Angelico, qui picturava le celo genuflecte?

Del septe galerias del Paradiso on crederea il que jecta rosas al terra. Qual in un nivate tepide e vagemente colorate, permane se le rosas in le turre, in le tegulate, in le arbores. Reguarda: tote le forte on face, con lor ornamento, delicate. Plus rosas, plus rosas, plus rosas...

Il pare, Platero, durante que sona le Angelus1, que iste vita nostre perde fortia quotidian, e que altere fortia de interior, plus alte, plus constante e plus pur, il face que toto, como en fontanas de gratia, on altia al stellas, que on accende jam inter rosas... Plus rosas... Le oculos tue, que tu non vide, Platero, e que altia mansuetemente al celo, esse duo belle rosas.
        </texto>
    </contento>
</documento>
