=== PedroRuiz/interlingua/assets/xml/document.dtd
<!-- una DTD para documento de Interlingua -->
<!ELEMENT documento (typo,designo?,data,incatenar?,taxinomia,autores,contento*) >
    
    <!ELEMENT typo              (#PCDATA)>                      <!-- declaration del typo de documento p.i.: traducction,information,linguistic, etc. -->
    
	<!ELEMENT designo           (#PCDATA)>                      <!-- schema de pagina, per defecto 'pages' -->
	
    <!ELEMENT data              (#PCDATA)>                      <!-- data expresate como aaaa-mm-dd -->
    
    <!ELEMENT incatenar         (vade*,veni*)?>                 <!-- OPTATIVE declarate solmente si iste documento on incatena con alteres -->
        <!ELEMENT vade          (#PCDATA)>                      <!-- documento al que vade -->
        <!ELEMENT veni          (#PCDATA)>                      <!-- documento del que veni -->
    
    <!ELEMENT taxinomia         (#PCDATA)>                      <!-- un description del contento del documento -->
    
    <!ELEMENT autores           (autor?)*>                      <!-- OPTATIVE autores (NO ON POTE REPETER)-->
        <!ELEMENT autor	        (nomine,retes*)>                 <!-- cata un del autores -->
            <!ELEMENT nomine 		(#PCDATA)>                  <!-- nomine del autor -->
            <!ELEMENT retes 		(#PCDATA)>                  <!-- un per cata retes social del autor ON POTE REPETER, p.i. email, twitter, facebook, etc -->
    
    <!ELEMENT contento          (titulo,imagine,texto*)>  <!-- declaration del contento (NO ON POTE REPETER) -->
		<!ELEMENT menu			(menunomine,menudata)*>
			
        <!ELEMENT titulo        (#PCDATA)>                      <!-- titulo (NO ON POTE REPETER)-->
        <!ELEMENT imagine       (#PCDATA)>                      <!-- imagine (NO ON POTE REPETER)-->
		<!ELEMENT texto       (#PCDATA)>                      
<![IGNORE[	
		<!ELEMENT texto 		(#PCDATA|nigre|cursiva|centrar|textitulo|teximagine|parve|ligamine)*>
			<!ELEMENT nigre		 	(#PCDATA)> 		
    		<!ELEMENT cursiva	 	(#PCDATA)>
    		<!ELEMENT centrar		(#PCDATA)>
			<!ELEMENT textitulo		(#PCDATA)>
			<!ELEMENT teximagine	(#PCDATA)>    	
			<!ELEMENT parve			(#PCDATA)>	
			<!ELEMENT ligamine		(direction,textoligamine)>
				<!ELEMENT direction		(#PCDATA)>
				<!ELEMENT textoligamine	(#PCDATA)>
]]>

=== PedroRuiz/interlingua/assets/xml/pages/protocollos_9.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE documento SYSTEM "../document.dtd">
<documento>
    <typo>Traductiones</typo>
    <data>20180115</data>
    <incatenar>
        <vade>https://interlingua.pedroruizhidalgo.es/documento/protocollos_10</vade>
        <veni>https://interlingua.pedroruizhidalgo.es/documento/protocollos_8</veni>
    </incatenar>
    <taxinomia>Sages de Sion, Protocollo IX</taxinomia>
    <autores>
        <autor>
            <nomine>Pedro Ruiz Hidalgo</nomine>
            <retes>@pedroruizhidalg</retes>
        </autor>
    </autores>
    <contento>
        <titulo>Protocollo IX</titulo>
        <imagine>https://interlingua.pedroruizhidalgo.es/assets/image/sages.jpg</imagine>
        <texto>/boldApplication del principios masonic pro imponer doctrina al populos. Destruction del poteres regnante. Importantia del atheismo. Dictatura del judeo-masoneria. Le terror. Servitores del judeo-masoneria. Conflicto inter le poter e le populo. Communitate de poter con le populo. Arbitrarietate liberal. Corruption del goim e su leges. Interpretation del leges. Metropoli.bold/

Al applicar le principios, vos tene que coler en cognoscer le character particular del nation, en cuje sino vos va a operar. Un application general e uniforme de principios no recoltara exito antes de que le education del nation en question ha essite regulamentate. Sed, applicante prudentemente nostre principios, vos discoperira que, in minus de dece annos, celle populo, pro obstinate que ha essite, se transformara e submittera a nos.

Quando sia le momento, nos substituera le locution del ordine que nos ostenta como divisa masonic Libertate, Equalitate e Fraternitate no por altere parolas, nec pro le mesme parolas transformate en ideas. Nos dicera: Le derecto al libertate, le deber de equalitate e le ideal del fraternitate; de ille modo, nos tenera incatenate al monstro. De facto, jam nos habera destruite onme governamentos del mundo, excepto le nostre, benque in theoria totevia remane alicunos pro destruer.

Actualmente, si alicun governamentos altia protestas contra nos, face lo pro pure formalismo e con nostre consentimento, pro que nos precisa de lor antisemitismo pro governar a nostre fratres minor e mantener cohesion inter illos. Non crede io necessari tractar exhaustivemente iste subjecto que jam ha essite scopo de innumerabile discutiones.

 In resume, nos non tene obstaculos in le camino. Le situation del governamento universal ante le lege es tanto robusta que un parola indica lo omne: Dictatura. Ego pote affirmar que in le momento actual nos es legislatores, nos dicta penas, nos sententia a morte o nos pardona; nos es alco assi como le general in chef que marcha al capite de omne exercitos. Nos governara con mano firme e voluntate de ferro. Nos ha apoderate del remanente de un poterose partito que governava in altere tempore e que ora tene ben fixate. Nos habe ambitiones dismensurate, ardente coditia, venganza sin pietate e odio reconcentrate.

De nos forni le terror que omne invade. Nos dispone servitores de omne opiniones e omne doctrinas: restauratores de monarchias, demagogos, socialistas, communistas e utopistas de omne typo. Tote illos collabora con nos. Cata qual, a lor forma, mina le poter e sfortia se pro derruer quanto on mantene in pede. Omne statos suffre con ille perturbationes, demanda calma e, pro amor al pace, illes es disposite a facer sacrificios; sed non sera concedite tregua usque recognosce aperta- e humilemente nostre governamento supreme international.
Populos reclama angustiate que es necessari resolver le question social mediante pactos internationales. Le divisiones del populo en partitos situa a omne in nostre manos, pro que, pro sustener lor debatto, illes precisa moneta, e le moneta tene nos.

Nos poterea diffider un alliantia inter intellectualitate del gentiles e le fortia ceca del populo, sed nos ha acquirite mensuras contra tal eventualitate. Inter ambe potentias nos ha levate un muro de timor reciproco. De Ille modo, nos appoia in le poter ceco del massas. Nos sera su unic chefs e conducera ubi nos conveni.

A fin de que le mano ceca non pote liberar se de nostre direction, nos debe permaner in contacto directe con le massas, si non personalmente, al minus mediante nostre fratres plus fidel.  Quando nos sia un poter recognoscite, nos dirigera directemente al populo in le strata public e instruera in in questiones politic tanto como nos judica necessari.

Como verificar que on docera al infantes in scholas rural? Nos debe pensar que quanto dice le delegate del governamento, e usque le minime persona regnante, sera cognoscite in tote le nation e es natural que le voce del populo divulga lo immediatemente.

Pro non destruer prematurmente institutiones del christian, nos habe retoccate habilemente, appropriante nos del controlos de su mechanismo. Antea illos functionava basse un regime sever, sed justo; nos ha substituite pro le liberalitate disordinate. Nos tocca le justitia, electiones, pressa, libertate individual e, supertoto, instruction e education, que es le sustentamento del libere existentia.

Decipiente, nos ha brutalisate e corrumpite al generation actual del gentiles con un education fundate in principios e theorias false inculcate pro nos mesme. Nos ha procedite pro super del leges in vigor, sin cambiar le in su essentia; Nos ha disfigurate mediante interpretationes contradictori con que nos ha attingite prodigiose resultatos. Il on ha potite verificar ille resultatos: nostre interpretation occultava le senso ver del leges, que on deveniva non intelligibile, nec governamentos ha potite disimbroliar tal intrication.

De hic nasceva le theoria del tribunal de conscientia. On vole dicer, que in certe casos, non debe fixar se al littera del lege nec judicar con arrangiamento al conscientia.

Comprehende se que nationes poterea brandir armas contra nos si nostre planes esserea prematurmente discoperite. Sed, in tal caso, nos ponerea in action le fortia formidabile de que nos dispone, e nos disincatenarea un manovra tanto terribile que facerea tremer al animas plus temerari. Profitante le retes ferroviari e systemas de cloacas nos facerea volar le grande metropolis con lor institutiones e tote lor documentos de stato.
        </texto>
    </contento>
</documento>

=== PedroRuiz/interlingua/assets/xml/pages/protocollos_10.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE documento SYSTEM "../document.dtd">
<documento>
    <typo>Traductiones</typo>
    <data>20180115</data>
    <incatenar>
        <vade>https://interlingua.pedroruizhidalgo.es/documento/protocollos_12</vade>
        <veni>https://interlingua.pedroruizhidalgo.es/documento/protocollos_10</veni>
    </incatenar>
    <taxinomia>Sages de Sion, Protocollo XI</taxinomia>
    <autores>
        <autor>
            <nomine>Pedro Ruiz Hidalgo</nomine>
            <retes>@pedroruizhidalg</retes>
        </autor>
    </autores>
    <contento>
        <titulo>Protocollo XI</titulo>
        <imagine>https://interlingua.pedroruizhidalgo.es/assets/image/sages.jpg</imagine>
        <texto>/boldProgramma del nove constitution. Alicun detalios re colpo de stato proponite. Gentiles tractate como arietes. Francmasoneria secrete e su logias de faciadas.bold/

Consilio de Stato servira pro confirmar le poter del Governamento. Sub le apparentia del corpore legislative, sera, in realitate, un committee pro le redaction de leges e derectos del governante.
Hic es como nos elaborara le nove constitution. Nos creara le lege, le derecto e tribunal:
/bold1.bold/ Como responsas al corpore legislative.
/bold2.bold/ Pro derectos presidential in forma de ordines general, per actos del senato e pro mandatos ministerial que procede del consilio de stato.
/bold3.bold/ Si resulta opportuno, per colpo de stato.

Un vice planate iste approximate modus agendi, nos examinara mensuras que sia valide pro finir le transformation del Stato in le senso desirate. Ego on refere al libertate de pressa, al derecto de association, al libertate de conscientia, al principio effective e a altere themas que habera de disparer del repertorio human o ser radicalmente alterate in le nove constitution.
Arrivate iste momento, nos potera publicar de un vice le conjuncto de nostre dispositiones. Plus avante, qualcunque cambio appreciabile resulara pelicurose: de esser facite le cambio in un clima de rigurose severitate, pote provocar desperation ante le temor de nove modificationes del mesme senso. Si, per contra, on actua a favor de disapprobationes siguiente, dira se que nos es errate (illo maculara le aura de infallibilitate del nove poter) o que, per timor, nos ha facite justes concessiones (que nemo ha regratiate). In un o altere caso, on incontrarea compromitte le prestigio del recente constitution. Nos interessa que, desde le die de su proclamation, quando le populos es stupefacite ante le terror e le perplexitate illos recognosce que nos es tan torte, invulnerabile, e poterose, que nos non contara con illos. Nos subestimara sue opiniones e desiros, essente disponite e in conditiones de reprimer omne expression o manifestation de ille aspirationes e de ille opiniones. Nostre autoritate sera indiscutibile: nos habera appoderate de un colpo de omne quanto nos precisa e non compartira con nemo. Tunc, illos claudera le oculos e sperara le disveloppamento del evenimentos.
Christian es un grege de arietes, e nos es le lupo! Vos jam sape que succede quando lupo entra in le grege!
Claudera le oculos ante omne. Promittera nos restabilir libertates confiscate un vice que le inimicos del pace, equemente que omne gruppos, habera essite reducite al impotentia. No necessita ego clarer que sperara indefinibilemente le volta al passato.
Pro que dede vos que nos ha inventate e inspirate al christian omne iste politica sin permitter comprender illa? Pro que attinger secretemente lo que nostre racia disperse no poterea arrivar apertemente? Iste ha essite le base del francmasoneria secrete, cuje designos no suspecta le inepte christian, convocate per nos al armea perceptibile del logias pro distraher reguardos de su proprie fratres.
Deo ha date a nos, sue electe populo, le dispersion, e in iste debilitate on trova le fortia que propelle nos al limine del dominio universal. Manca jam pauco pro edificar super iste erection.</texto>
    </contento>
</documento>

=== PedroRuiz/interlingua/assets/xml/pages/protocollos_8.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE documento SYSTEM "../document.dtd">
<documento>
    <typo>Traductiones</typo>
    <data>20180115</data>
    <incatenar>
        <vade>https://interlingua.pedroruizhidalgo.es/documento/protocollos_9</vade>
        <veni>https://interlingua.pedroruizhidalgo.es/documento/protocollos_7</veni>
    </incatenar>
    <taxinomia>Sages de Sion, Protocollo VIII</taxinomia>
    <autores>
        <autor>
            <nomine>Pedro Ruiz Hidalgo</nomine>
            <retes>@pedroruizhidalg</retes>
        </autor>
    </autores>
    <contento>
        <titulo>Protocollo VIII</titulo>
        <imagine>https://interlingua.pedroruizhidalgo.es/assets/image/sages.jpg</imagine>
        <texto>/boldFraude in procedimentos. Collaboratores del judeo-masoneria. Nostre scholas special e su scopo. Economistas e millionarios. A qui on debe confider le postos importantes del governamento.bold/

Nos debe appropriar de omne instrumentos e medios que nostre adversarios pote emplear contra nos. Nos usara subtilitate de delicatessas del lingua juridic quando nos tene que pronunciar sententias osate o injuste. Il es necessari exprimer ille judicamentos in terminos que pare moral, rationabile e justo ante le populo.

Nostre governamento habera de incircular se del elementos plus poterose de aquelle civilisation ubi on debe mover se. In su milieu abundara publicistas, jurisconsultos, administratores, procuratores, diplomaticos... es dicer, homines preparate pro nos in scholas special.

Celle homines cognoscera le secretos del existentia social, le lingua politic, le sentimentos del corde human, e de su cordas plus sensibile (super celle habera de actuar multe vices). Iste cordas constitue le spirito del gentiles, su bon e mal qualitates, su tendentias e su vitios, le particularitates de classe e condition. Il permane ben intendite que collaboratores genial de nostre governamento no exira del gentiles, habituate a affectar su travalios administrative sin coler de su utilitate o finalitate. Administratores christian signa papiros que no lege e servi pro interesse o ambition.

Nos plenara nostre governamento de economistas. Scientias economic es le themas primordial que nos insenia al judeos. Nos tenera in nostre ambiente un universo de bancheros, industriales, capitalistas e supertoto, millionarios: al final le moneta decidera toto.

 Intertanto nos non es completemente secur de adjudicar illes le altos postos del governamento al judeos, nos nominara personas cuje antecedentes e reputation sia tan mal que ha facite un abysmo inter illos e le nation. Illes essera homines tal que, in caso de disobedir nostres ordines, tene que sperar un condemna o un exilio. Isto on facera con le objecto de obligar illes a defender nostre interesses usque le ultime consequentias.</texto>
    </contento>
</documento>

=== PedroRuiz/interlingua/assets/xml/pages/coopera.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE documento SYSTEM "../document.dtd">
<documento>
    <typo>web</typo>
    <data>20180108</data>
    <incatenar>
        <vade></vade>
        <veni>http://interlingua.pedroruizhidalgo.es</veni>
    </incatenar>
    <taxinomia>Coopera con nos</taxinomia>
    <autores>
        <autor>
            <nomine>Pedro Ruiz Hidalgo</nomine>
            <retes>@pedroruizhidalg</retes>
            <retes>interlingua@pedroruizhidalgo.es</retes>
        </autor>
    </autores>
    <contento>
        <titulo>Iste projecto es aperte pro te!</titulo>
        <imagine>https://interlingua.pedroruizhidalgo.es/assets/image/cooperacion.jpg</imagine>
        <texto>Como si essera un limite de un function que non pote attinger le final, iste projecto es ass√≠. Il es in un constante evolution, forsan revolution, que face de illo un loco aperto e in constante cambio.
        
        Si tu posede o cognosce un projecto que incatenar o, forsan, tu vole adjutar a disveloppar o contribuer hic, per favor contacta nos.
        
        /link"https://interlingua.pedroruizhidalgo.es/documento/instructiones_pro_collaborar"/l_Sape plus de nostre systemal_/ link/.
        
        </texto>
    </contento>
</documento>

=== PedroRuiz/interlingua/assets/xml/pages/oh_fortuna.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE documento SYSTEM "../document.dtd">
<documento>
    <typo>Traductiones</typo>
    <data>20180116</data>
    <incatenar>
        <veni>https://interlingua.pedroruizhidalgo.es/leger</veni>
    </incatenar>
    <taxinomia>Canto medieval "Oh Fortuna"</taxinomia>
    <autores>
        <autor>
            <nomine>Pedro Ruiz Hidalgo</nomine>
            <retes>interlingua@pedroruizhidalgo.es</retes>
            <retes>@pedroruizhidalg</retes>
        </autor>
    </autores>
    <contento>
        <titulo>Carmina Burana: Oh Fortuna</titulo>
        <imagine>https://interlingua.pedroruizhidalgo.es/assets/image/oh_fortuna.jpg</imagine>
        <texto>Oh Fortuna,
como le luna
stato variabile
sempre se cresce
o se decrescentia;

Vita abominabile,
nunc opprime
e pois cura
como en un joco
a le provressa
e al poter
disgelava como le glacie.

Sorte monstruose
e vacue,
tu rota gira,
stato malefic,
le sanitate es vacua,
sempre se funde,
in umbra
e velante
etiam a me occide;
nunc in le joco
io porto mi dorso nude
por tu malitia.

Le sorte en le sanitate
e in la virtute
es contra me,
illa me pulsa
e me frena,
sempre me ha sclavo.
In iste hora,
sin retardo,
musica les cordas que vibra,
quia le sorte 
annihila al forte,
vos plorar omnes con me.</texto>
    </contento>
</documento>

=== PedroRuiz/interlingua/assets/xml/pages/platero_5.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE documento SYSTEM "../document.dtd">
<documento>
    <typo>Traductiones</typo>
    <data>20180105</data>
    <incatenar>
        <vade>http://interlingua.pedroruizhidalgo.es/documento/platero_6</vade>
        <veni>http://interlingua.pedroruizhidalgo.es/documento/platero_4</veni>
    </incatenar>
    <taxinomia>Le primavera</taxinomia>
    <autores>
        <autor>
            <nomine>Pedro Ruiz Hidalgo</nomine>
            <retes>@pedroruizhidalg</retes>
            <retes>interlingua@pedroruizhidalgo.es</retes>
        </autor>
    </autores>
    <contento>
        <titulo>Platero e io</titulo>
        <imagine>https://interlingua.pedroruizhidalgo.es/assets/image/platero_5.jpg</imagine>
        <texto>Guai, que splendor e que odores!
Guai, como ride le pratos!
Guai, que canto matinal on audi!
			Romance popular.
        
        
        </texto>
        <texto>In mi dormitar matinal, me irrita un indiabolate clamor de infantes. Finalmente, sin poter dormir plus, io reposa me, desperado, en le lecto. Alora, al vider le campo trans le fenestra aperte, io comprehende que qui face le agitation es le aves.

Io exi al cortil e regratia al Deo del die blau. Libere concerto de beccos, fresc e sin fin! Le hirundine crispa, capriciose, su canto en le puteo; sibila le merla super le orange cadite; de foco, le oriolo balbutia in le robore; le passere, ride sovente e largemente in le culmine del eucalypto; e, in le grande pino, le canarios discute sin possessor.

Como esse le deman! Le sol pone in terra su gaudio de argenta e de auro; papiliones de cento colores joca por tote locos, inter le flores, por le domo, in le fontana. Ubicunque, el campo on aperi en detonationes, en strideres, en un bullir de vita san e nove.

Il pare que nos esse intro de un grande favo de luce, que esserea le interior de un immense e, calide rosa incendite.</texto>
        
    </contento>
</documento>

=== PedroRuiz/interlingua/assets/xml/pages/platero_1.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE documento SYSTEM "../document.dtd">
<documento>
    <typo>Traductiones</typo>
    <data>20180104</data>
    <incatenar>
        <vade>http://interlingua.pedroruizhidalgo.es/documento/platero_2</vade>
        <veni>http://interlingua.pedroruizhidalgo.es/documento/platero_0</veni>
    </incatenar>
    <taxinomia>La elegia</taxinomia>
    <autores>
        <autor>
            <nomine>Pedro Ruiz Hidalgo</nomine>
            <retes>@pedroruizhidalg</retes>
            <retes>interlingua@pedroruizhidalgo.es</retes>
        </autor>
    </autores>
    <contento>
        <titulo>Platero e io</titulo>
        <imagine>https://interlingua.pedroruizhidalgo.es/assets/image/platero_1.jpg</imagine>
        <texto>Platero es parve, hirsute, suave; tanto blande pro foras, que on dicerea tote de coton, que no habe ossos. Solo le speculos de lignite polite de su oculos es dur qual duo coleopteros de vitro nigre.</texto>
        <texto>Io lo lassa distaccate, e on va al prato, e ille caressa tepidemente con su muso, racente a pena, le floretto rosee, celeste, e rubie... Io appella lo dulcemente, “Platero?”, e veni a me con un trotto contente que il pare que on ride, en io non sape que tintinnar ideal...</texto>
        <texto>Ille mangia quanto io le da. Habe gusto pro le oranges mandarina, le uvas moscatel(1), tote de ambra, le ficos morate, con lor crystallin gutta de melle.</texto>
        <texto>Ille es tenere e caressabile eque un puero, eque un puera...; sed forte e sic como un petra. Quando io passa, super ille, le dominicas, pro le ultime vicos del village, le homines del campo vestite sin macula, e pausatemente, on permane vidente lo.</texto>
        <texto>— Il habe aciero...</texto>
        <texto>Ille habe aciero. Aciero e argenta de luna, al mesmo tempore..</texto>
        <texto>(1) N.T. Moscatel es un typo de uva blanc o purpuree. Lor origene possibilemente es de Alexandria. Iste typo de uva es multo appreciate en Andalusia ubi ha multe plantationes. On obtene un vino del mesme nomine multo sucrate que iste traductor recommenda, cautemente, al lector.</texto>
        
    </contento>
</documento>

=== PedroRuiz/interlingua/assets/xml/pages/protocollos_7.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE documento SYSTEM "../document.dtd">
<documento>
    <typo>Traductiones</typo>
    <data>20180115</data>
    <incatenar>
        <vade>https://interlingua.pedroruizhidalgo.es/documento/protocollos_8</vade>
        <veni>https://interlingua.pedroruizhidalgo.es/documento/protocollos_6</veni>
    </incatenar>
    <taxinomia>Sages de Sion, Protocollo VII</taxinomia>
    <autores>
        <autor>
            <nomine>Pedro Ruiz Hidalgo</nomine>
            <retes>@pedroruizhidalg</retes>
        </autor>
    </autores>
    <contento>
        <titulo>Protocollo VII</titulo>
        <imagine>https://interlingua.pedroruizhidalgo.es/assets/image/sages.jpg</imagine>
        <texto>/boldScopo de altia de armas. Fermentation, luctas e discordia in omne le mundo. Submittente del gentiles verso de guerras interne e pro le guerra mundial. Secreto considerate como arte del politica e de judeo-masoneria. Pressa, opinion public e nostre triumpho. Seniores american, japonese e chinese.bold/

Intensification del servicio militar e augmento del fortias de policia es essential pro realisation del planes indicate.  Il es necessari que, extra de nostre orbita, le pais permane reducite a un grande massa proletari de ubi haurir individuos convertite in soldatos e agentes de policia submissos a nostre causa.

In tote Europa, e con le adjuta de Europa, nos debe suscitar in tote le resto de continentes le discordia, dissensiones e mutua hostilitate. Assi nos tenera un duple avantage: in prime loco, illos respectara nos in omne paises e assi illos sapera que nos pote, quando nos vole, provocar le disordine restabilir le ordine, per altere, omne statos accostumara a considerar nos como un carga necessari; in secunde loco nos involvera con intrigas al ministerios de tote governamentos, sia pro nostre politica o per medio del contractos commercial e obligationes financiari.

Pro attinger iste scopo, sera necessari recurrer a infinitate de insidias e artificios durante negotiationes e debattos; sed quando nos arriva a isto que es appellate le lingua official, nos adoptara le tactica opposite, fingente ser summemente honorabile e consiliator. De iste modo le governamentos del gentiles, a qui nos ha accostumate a vider unicamente le latere plus impressionante del negotios que es sempre nos ha presentate, nos considerara totevia le benfacente e salvatores del humanitate.

Nos ha de star preparate pro travaliar con qui on oppone a nostre projectos. Si il esserea necessari, que le pais vicino declara le guerra al nation que pretende blocar nos. Sed si ambe on reuni contra nos, tunc nos discatenara un guerra mundial.

In politica, le triumpho definitive depende essentialmente del reserva con que on ha protegite le plan a effectuar. Actos de un diplomatico non debe corresponder nunquam con su parolas.

Jam le projecto mundial on approxima al finales planate anteriormente. Pro attinger su exito total, nos necessita convincer al governamentos del gentiles per lo que vulgarmente on appella opinion public. Le criterio popular ha essite redisposto pro nos per le pressa: ille grande potentia es in nostre manos in quasi su totalitate.

Arrivara le momento de demonstrar que tote governamentos europee del goim es slavisate. Nos submittera a un de illos al grande proba de nostre poter. Nos on servira de ultrage e crimines, e nos servira del terror. Si esserea le caso que, indignate, le alteres on ponerea in contra nostre, nos responderea con le poteres bellic american, chinese o japonese.</texto>
    </contento>
</documento>
