=== PedroRuiz/interlingua/assets/xml/document.dtd
<!-- una DTD para documento de Interlingua -->
<!ELEMENT documento (typo,designo?,data,incatenar?,taxinomia,autores,contento*) >
    
    <!ELEMENT typo              (#PCDATA)>                      <!-- declaration del typo de documento p.i.: traducction,information,linguistic, etc. -->
    
	<!ELEMENT designo           (#PCDATA)>                      <!-- schema de pagina, per defecto 'pages' -->
	
    <!ELEMENT data              (#PCDATA)>                      <!-- data expresate como aaaa-mm-dd -->
    
    <!ELEMENT incatenar         (vade*,veni*)?>                 <!-- OPTATIVE declarate solmente si iste documento on incatena con alteres -->
        <!ELEMENT vade          (#PCDATA)>                      <!-- documento al que vade -->
        <!ELEMENT veni          (#PCDATA)>                      <!-- documento del que veni -->
    
    <!ELEMENT taxinomia         (#PCDATA)>                      <!-- un description del contento del documento -->
    
    <!ELEMENT autores           (autor?)*>                      <!-- OPTATIVE autores (NO ON POTE REPETER)-->
        <!ELEMENT autor	        (nomine,retes*)>                 <!-- cata un del autores -->
            <!ELEMENT nomine 		(#PCDATA)>                  <!-- nomine del autor -->
            <!ELEMENT retes 		(#PCDATA)>                  <!-- un per cata retes social del autor ON POTE REPETER, p.i. email, twitter, facebook, etc -->
    
    <!ELEMENT contento          (titulo,imagine,texto*)>  <!-- declaration del contento (NO ON POTE REPETER) -->
		<!ELEMENT menu			(menunomine,menudata)*>
			
        <!ELEMENT titulo        (#PCDATA)>                      <!-- titulo (NO ON POTE REPETER)-->
        <!ELEMENT imagine       (#PCDATA)>                      <!-- imagine (NO ON POTE REPETER)-->
		<!ELEMENT texto       (#PCDATA)>                      
<![IGNORE[	
		<!ELEMENT texto 		(#PCDATA|nigre|cursiva|centrar|textitulo|teximagine|parve|ligamine)*>
			<!ELEMENT nigre		 	(#PCDATA)> 		
    		<!ELEMENT cursiva	 	(#PCDATA)>
    		<!ELEMENT centrar		(#PCDATA)>
			<!ELEMENT textitulo		(#PCDATA)>
			<!ELEMENT teximagine	(#PCDATA)>    	
			<!ELEMENT parve			(#PCDATA)>	
			<!ELEMENT ligamine		(direction,textoligamine)>
				<!ELEMENT direction		(#PCDATA)>
				<!ELEMENT textoligamine	(#PCDATA)>
]]>

=== PedroRuiz/interlingua/assets/xml/pages/instructiones_pro_collaborar.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE documento SYSTEM "../document.dtd">
<documento>
    <typo>Web</typo>
    <data>20180118</data>
    <incatenar>
        <veni>https://interlingua.pedroruizhidalgo.es</veni>
    </incatenar>
    <taxinomia>Instrucctiones pro collaborar</taxinomia>
    <autores>
        <autor>
            <nomine>Pedro Ruiz Hidalgo</nomine>
            <retes>interlingua@pedroruizhidalgo.es</retes>
            <retes>@pedroruizhidalg</retes>
        </autor>
    </autores>
    <contento>
        <titulo>Collaborar</titulo>
        <imagine>https://interlingua.pedroruizhidalgo.es/assets/image/collaborar.jpg</imagine>
        <texto>/titBasse constructiontit/ Nos es aperte a qualcunque collaboration que es relationate con Interlingua: contos, novelas, articulos re linguage, derivate collangs, comics, etc.
        Nostre systema es simple. Es archivos xml que qui vole collaborar pote solicitar /link"mailto:interlingua@pedroruizhidalgo.es"/l_collaborar pote solicitar hicl_/ link/ con un email.
        
        /titMetalinguagetit/ Per rationes de procceso computational, que non essera commentates, nostre archivo xml no pote continer marcas de html. Sed nos ha disveloppate un metalinguage que simula iste marcas e solmente pote ser usate in nostre systema.
        
        /titMarcastit/ Cata un del marcas ha un apertura "/marca" e clausura "marca/":
        Iste marcas es:
       'bold', pro texto /boldnigrebold/.
		'em', pro enphatisar con texto in /emitalicaem/.
		'center' /centerpro centrar texto in schermo.center/
		/tit'tit' pro titular.tit/
		'img', pro imagine. Post iste marca le direction del imagine sera inter virguletas ".
		'small' pro /smallparve textosmall/.
        
		'link', pro ligamines. Le direction del ligamine essera descripte inter virguletas. Iste marca es special. Como iste pagina es scripte in iste sistema non pote ser scribite le marcas real perque illo supone que essera proccesate.
        pro iste exemplo de link on scribe le barra contrari, que non causara necun effecto. Marca link es assi.
        \link"http://google.com"\l_Googlel_\ link\.
        
        Pulsa /link"https://interlingua.pedroruizhidalgo.es/documento/coopera"/l_coopera con nosl_/ link/.
        </texto>
    </contento>
</documento>

=== PedroRuiz/interlingua/assets/xml/pages/protocollos_4.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE documento SYSTEM "../document.dtd">
<documento>
    <typo>Traductiones</typo>
    <data>20180115</data>
    <incatenar>
        <vade>https://interlingua.pedroruizhidalgo.es/documento/protocollos_5</vade>
        <veni>https://interlingua.pedroruizhidalgo.es/documento/protocollos_3</veni>
    </incatenar>
    <taxinomia>Sages de Sion, Protocollo IV</taxinomia>
    <autores>
        <autor>
            <nomine>Pedro Ruiz Hidalgo</nomine>
            <retes>@pedroruizhidalg</retes>
        </autor>
    </autores>
    <contento>
        <titulo>Protocollo IV</titulo>
        <imagine>https://interlingua.pedroruizhidalgo.es/assets/image/sages.jpg</imagine>
        <texto>/boldDiverse phases de un republica. Action occulte del logias. Libertate e fide. Concurrentia international del commercio e industria. Le speculation. Culto al auro.bold/

Omne republica experimenta diverse periodos. Initia se como un ceco que fulla quanto es a su passo. Post illo, aperi se passo al demagogo que face germinar le anarchia e cultiva lo con finalitate de collectar le despotismo; non on tracta de un despotismo official, nec coperite. Sed il on lassa sentir. Generalmente, le fulla es dirigite pro alicun societate secrete que, occultate post su agentes, on monstra audace e sin scrupulos. Iste poter vadera a locar su agentes ubi melior conveni. Decite cambios correspondera al appetentia de disembarassar se de vetule servitores cuje servicios resulta jam costose.

Qui potera disthronar un poter occulte? Nostre fortia es invisibile. Le logia masonic servi pro occultar nostre planes. Le uso que no face de iste poter, equemente que le implaciamento de nostre quartieros general, sempre essera ignorate pro le public.

De esser bassate in le religion, in le fide in Deo e in le fraternitate human, le libertate poterea ser inoffensive; si libertate distacca ideas de equalitate, que contradice leges del creation (que a su vice stabili subordination), poterea exister in le governamento sin ser prejudicial al prosperitate del populo. Con tal fide, le populo lassarea governar pro le parochias e marcharea humile e tranquillo base le gerentia de lor pastores spiritual, submittite in le terra al divin providentia. Pro illo il es necessari accender del spirito del christian le conception mesme de Deo, substituente lo pro calculos arithmetic e pro necessitates material del vita.

Pro no eveliar suspiciones del christian a proposito de nostre politica, il es precise intertener illos e appellar su attention del loco del commercio e del industria. De ille forma, le nationes luctara pro su interesses particular, sin notar le tracia del inimico commun. Sed, pro que libertate pote disaggregar e ruinar le vita social del gentiles, il es necessari stabilir le speculation. De ille forma, on consequera evitar que gentiles retene ricchessa procedente del production del solo e del industria. Pro via del speculation, omne economia cadera in nostre manos.

Le lucta pro le suprematia e le chocs in le mundo del negotios creara un societate disincantate, egoistic e sin corde. Ille societate sentira indifferentia pro le religion e un profunde repugnantia pro le alte politica. Su guida essera le calculo e su culto al passion del auro. Homines facera omne fortias inimaginabile pro consequer le sparnio que pote proportionar illes le benes material. Tunc, le classe inferior de christian on unira in contra de nostre rivales plus intelligente; Illes non facera lo pro ideales, non mesmo pro desiros de ricchessa, illes facera pro odio al classes accommodate.</texto>
    </contento>
</documento>

=== PedroRuiz/interlingua/assets/xml/pages/protocollos_12.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE documento SYSTEM "../document.dtd">
<documento>
    <typo>Traductiones</typo>
    <data>20180115</data>
    <incatenar>
        <vade>https://interlingua.pedroruizhidalgo.es/documento/protocollos_13</vade>
        <veni>https://interlingua.pedroruizhidalgo.es/documento/protocollos_12</veni>
    </incatenar>
    <taxinomia>Sages de Sion, Protocollo XII</taxinomia>
    <autores>
        <autor>
            <nomine>Pedro Ruiz Hidalgo</nomine>
            <retes>@pedroruizhidalg</retes>
        </autor>
    </autores>
    <contento>
        <titulo>Protocollo XII</titulo>
        <imagine>https://interlingua.pedroruizhidalgo.es/assets/image/sages.jpg</imagine>
        <texto>/boldLibertate secundo judeo-masoneria. Pressa sub poter judeo-masonico. Controlo de pressa. Progresso secundo francmasoneria. Transcendentia del pressa. Solidarietate inter masoneria e pressa actual. Inflammation del exigentias social provincial. Infallibilitate del nove regime.bold/

Nos definira del sequente forma le parola libertate (proque pote esser interpretate de diverse formas). Libertate es le derecto a facer lo que permitte le lege. In nostre die, tal interpretation collocara omne libertate in nostre manos; secundo le programma exponite, leges demolira o instituera lo que nos conveni.

Con pressa nos operara del sequente modo: que papiro representa actualmente le pressa? Illo servi pro incender le passiones e mantener le egoismos partitario. Il es vacue, injuste, fabulator, e majoritate de personas non comprehende su utilitate. Nos sigillara illo e ponera freno, como nos facera con resto de opera impresse: De que servira disfacer nos del pressa si nos es le scopo del resto de publicationes e de libros? Nos transformara le publicitate, que ora es tan dispendiose; il es gratias a ille que nos pote censurar le jornales. Nos establira un imposto special pro le pressa. Requirera nos un participation in le profitos de quotidianes e editoriales. Assi, nostre governamento essera a salvo del attaccos del pressa. Opportunmente, nos imponera mulctas immisericordemente. Tanto mulctas como impostos ingrossara le coffros del stato.

Il es certe que quotidianes del partitos poterea resultar plus perniciose que le perdita de su moneta; de ser assi, nos expungera a radice de su secunde accurrer. Nemo habera macular le mytho de nostre infallibilitate governamental. Pro expunger un quotidian, nos dicera que agita le animos sin ration nec motivo.

On habera de notar que, inter le quotidianos que nos attacca, habera multo create per nos mesme. Istos attaccara exclusivemente le punctos que nos desira modificar.

Sin nostre approbation, nihil sera communicate al societate. Isto ultime ya on ha attingite. Hodie, notitias de omne partes del mundo es recipite per diverse agentias que centralisa las. Ille agentias es purmente nostre e revela solmente lo que nos permitte publicar.

Actualmente, nos ha sapite captar del animo del societates christian de tal modo que, in omne partes, mira le eventos mundial trans nostre prismas que nos colloca ante lore oculos. Jam non ha muros in nemo stato que impedi nos entrar a le que christianos denomina stupidemente secrete de statos. Que sera quando nos sia dominos recognoscite del universo in le persona de nostre rege universal?

Qui inter nos ignora que benes illusori conduce directemente al somnos absurde? De tal somnos on ha originate le relationes anarchic del homines inter ipse e con le poter. Le progresso, o melior dicite, le representation de illo ha propitiate ideas de multiple e illimitate emancipationes.

Omne aquelle que nos appella liberal es anarchista, si ben non de facto, al minus de pensamento. Protestante pro le unic placer de susurrar, illes perseque le illusiones del libertate e cade in le anarchia.

Que nos torna al pressa. Nos imponera taxas como a omne quanto sia imprimite. Essera impostos ascendente secundo el numero de papiros. Publicationes de minus de trenta paginas, registrate como brochures, parara duple de tributos; on cerca assi, per un loco, reducer le numero de brochures, que es le pejor del venenos, e, per altere loco, obligar al scriptores a producer libros tan longos e caros que sia pauco legite. Per contra, celles que nos edita pro le ben commun e con le tendentia stabilite essera economic e legite per totes. Impostos finira con vacue desiro de scriber, e medo a sanction submittera al litteratos.

Si alicun volve su penna contra nos, non trovara qui vole imprimer su scriptos. Antea de consentir imprimer un opera, le editor o impressor consultara al autoritates a fin de obtener autorisation necessari. De iste modo, nos cognoscera anticipatemente le imboscadas que nos face e contraattaccara nos, mediante explicationes con antecedentes re le caso tractate.
Litteratura e jornalismo es le medios educative plus importante. Per illo, nostre governamento sera le proprietari del majoritate del quotidianes. Assi, le influentia perniciose del pressa particular sera neutralisate e nos obtenera un autoritate enorme super le public. Si nos autorisa le publication de dece quotidianes, nos fundara trenta del nostre.
Quotidianes que nos edita sera, apparentemente, de tendentias e opiniones opponite. Illo habera de inducer confidentia a omnes e habera de attraher, sin suspicion, a adversarios que cadera in le trappa e devenira inoffensive.

In prime loco, nos displicara le organos de character official; ille sempre velera per nostre interesses e non nos habera de mancar le somno. In secunde loco, collocara nos le officiose, cuje papiro sera el de attraher al indifferente e al amorphe. In tertie loco, installara al pretense opposition: al minus un quotidian collaborara con nos como antipoda de nostre ideas. Nostre adversarios prendera a ille false oppositor como su alliate e revelara a nos mediante ille.

Nostre quotidian sera de omne tendentias: aristocratic, republican, revolutionari, e usque anarchic; Isto, naturalmente, intertanto dura le constitution. Tenera, como le deo hindu Visnu, cento manos, cata un del qual accelerara le transmutation del societate. Iste manos conducera le opinion como melior sia conveniente a nostre interesses (un homine alterate perde la facultate de rationar e on abandona facilemente al suggestion). Imbecille qui crede sequer le opinion de su partito repetera nostre opinion, o qual nos conveni. On videra sequente al organo de su partito sin saper que, realmente, escorta le bandiera que nos porta ante lore oculos.

Pro gerer in iste rumbo a nostre exercito de jornalistas, nos organisara iste labor cautemente. Sub le nomine de Bureau Central del Pressa, nos stabilira reuniones litterari ubi nostre agentes dara, sin suspicion de nemo, le parola de ordine e normas. Discutente e contradicente nostre initiativas de un forma superficial, sin penetrar el fundo del question, sustenera inutile polemicas con le jornales official a fin de procurar medios de pronunciar nos plus clarmente, qualcosa que no es conveniente facer durante le prime declarationes official.
Istos attaccos servira, in plus, pro que nostre vassallos judica garante le libertate de parola. Assi, nostre agentes possedera pretextos pro affirmar que qui nos impugna es un charlatan sin argumentation pro refutar seriemente nostre projectos.

Tal processos, non advertite pro le opinion public, sed secur, nos trahera certemente attention e confidentia public. Gratias a illos, nos agitara o calmara le animos in questiones politic secundo sia necessari, convincente o suscitante dubitas, publicante le veritate o falsitate, confirmante o contradicente secundo le effecto desirate, sed comparante sempre le terreno que nos habera de calcar.

Nos vincera a nostre adversarios proque illos non disponera de organos que pote reger le opinion usque ultime consequentias, como nos. No tenera, non mesmo, necessitate de longe e profunde refluctuationes. In caso de necessitate, nos refutara energicamente in le pressa officiose le globos de essayo lanceate per nos mesme in le tertie categoria de nostre pressa.
In iste momento, existe jam solidarietate francmasonic intra del jornalismo francese. Omne organos del pressa es ligate inter ipse pro le secrete professional; como vetule augures, nemo de su integrante revelara le secrete sin reciper ordine de facer lo. Necun jornalista osara trair iste secreto, jam que no serea admittite al profession qui non tene in su passato alicun manco de serietate vergoniose: in caso de infidelitate, ille macula sera immediatemente revelate. Durante que ille stigmas sia cognoscite solmente pro un pauco, le aureola del jornalista sequera attrahente nos le opinion del majoritate qui seque ille con enthusiasmo.

Durante que non nos disfructa del poter absolute, nos tenera necessitate de fullar capitales con opiniones del populo provincial, es dicer, pro le majoritate manipulate pro nostre delegate. Il es necessari que in capitales, in momento critic, non on discute le facto consummate per haber essite jam acceptate pro le majoritate provincial.

Quando nos passa al nove regime que prepara le arrivate de nostre regno, nos potera tolerar le revelation del dishonestitate public pro le pressa. Sera necessari que on crede que le nove regime satisface de tal modo a tote que usque le crimines disparere. Le casos de manifestationes criminal cognoscite solmente pro le victimas e testes presential.
</texto>
    </contento>
</documento>

=== PedroRuiz/interlingua/assets/xml/old.document.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE documento SYSTEM "../document.dtd">
<documento>
    <typo></typo>
    <data></data>
    <taxinomia></taxinomia>
    <autores>
        <autor>
            <nomine></nomine>
            <retes></retes>
            <retes></retes>
        </autor>
    </autores>
    <contento>
        <titulo></titulo>
        <imagine></imagine>
        <texto></texto>
    </contento>
</documento>

=== PedroRuiz/interlingua/assets/xml/pages/stato_de_maxime_incompetentia.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE documento SYSTEM "../document.dtd">
<documento>
    <typo>Scriptes de autor</typo>
    <data>20180116</data>
    <incatenar>
        <veni>https://interlingua.pedroruizhidalgo.es/leger</veni>
    </incatenar>
    <taxinomia>Stato de Maxime Incompetentia</taxinomia>
    <autores>
        <autor>
            <nomine>Pedro Ruiz Hidalgo</nomine>
            <retes>interlingua@pedroruizhidalgo.es</retes>
            <retes>@pedroruizhidalg</retes>
        </autor>
    </autores>
    <contento>
        <titulo>Un situation real del politica en Espania</titulo>
        <imagine>https://interlingua.pedroruizhidalgo.es/assets/image/incompetencia.jpg</imagine>
        <texto>/titLe stato del maxime incompetentia.tit/

Il ha un burla communmente explicate in interprisas, super toto, in ambitos de computation. Ille es assi: en qualcunque interprisa es contactate un travaliator. Ille travaliator es bon, logicamente, el prospera. Su empleatores crede que el seque essente un bon travaliator que merita esser ascendite altere vice.  Assi continua le conto usque nostre homine arriva a tal posto in que ya non pote esser ascendite, ya non prospera. Ergo ille ultime posto de responsabilitate es su stato de maxime incompetentia.

Situation politica en Espania es regite per un pugnata de personas qui non pote esser ascendite.

Nos ha un rege, qui ha hereditate su posto perque su patre ha dimittite e lassate en hereditate. Realmente ille ha tenite necun governamento in Espania durate su regno. Io non parlara plus re iste persona perque io es de credentia republican: In Espania ha un lege que prohibe parlar contra le monarchia.

Etiam, ha un politico appellate Mariano Rajoy, del Partito Popular, qui ha essite presidente del governamento de Espania desde decembre de 2011 usque 11 decembre de 2015, date ubi comencia a exercer como presidente in functiones.

Altere actor in queste theatro burlesc es Pedro Sánchez, electe secretario general (presidente) del Partito Socialista post mal resultates de Alfredo Pérez Rubalcaba in electiones europee de 2014. El obtene la direction de su partito quando iste habeva le pejor resultato in su longe historia. Assi, Pedro Sánchez, ha un mission suicida, consistente en facer flotar altere vice a un partito. Benque, como secretario general, el sta circumferite e subjecto a presidentes de communitates autonomes qui mantene su posto con plus possibilitates de futuro que el mesme presidente del partito. Question que face a Sánchez presse de al hora de executar decisiones. Non obstante, Partito Socialista ha parite non distinguibile del politicas neoliberal en decennios.

Procedente de Catalonia, region que pretende su independentia del stato espaniol, Albert Rivera, del Partito Citatano, es contrari al separation de Catalonia de Espania. Il comenciava como un partito regional e saltava al ambito national con una nove derecta que totevia plus liberal que Partito Popular, pretende le libration de obligationes por parte del stato al citatanos. Per exemplo, pensiones, sanitate, justitia e education private. Assi, secundo mi impression, su politica pote liberar al Stato de cargas economic.

Por ultime, Pablo Iglesias, professor de scientia politica de Universitate Complutense, e vetule militante de partitos e associationes de sinistra, comencia su action post movimento appellate «15M» ubi le populo espaniol on lanceava al strata pro demandas de plus democratia, libertate, digne salarios e conditiones socio-economic melior. 

Partito de Pablo Iglesias es appellate Podemos (/emNos poteem/), benque ille partito ha concurrite juncte a Izquierda Unida al ultimas electiones. Izquierda Unida es un coalition de partitos de sinistra que ha essite aggruppate en iste organisation post le fracasso del euro communismo.

Con istes personas e positiones, Espania convoca un secunde convocato de electiones general en 26 de junio del presente anno 2016. Importante saper que habeva altere electiones general el 20 de decembre de 2016. Iste es fallite e non ha essite possibile formar un governamento.

In Constitution espaniol rege es qui designa a un deputato pro formar governamento. Sed, nostre constitution non es presidential, io vole dicer, es le Congresso del Deputatos qui debe designar e seliger al presidente del Governamento, que a su vice, debe esser proponite por le rege. Traditionalmente, benque nostre democratia ha quaranta annos plus o minus, sempre qui a essite designate pro le rege ha potite formar governamento debite al traditional  bipartitismo essente usque annos septanta. 

Sed le nove situation a cambiate. Le nove situation politica face que el populo on pronuncia sin majoritates pro formar governamento al vice que politicos non comprehende ille nove situation.

In passate, le partitos Popular e Socialista, ha alternate governamento con adjuta, caso de esser necessari, con adjuta (basse concessiones politicas e social) de partitos catalanes e bascos, adjuta (concessiones) que ora non es possibile jam que le irruption del nove actores politic propitia un situation ubi non ha majoritates, ergo, politicos debe altiar accordos, cosa pro que ille ha demonstrate un total incapacitate.

Effectivemente ha un divortio inter populo e sue governantes. 

/boldSi, iste es le stato me maxime incompetentia.bold/
/smallAutor del texto:Pedro Ruiz Hidalgo.small/

</texto>
    </contento>
</documento>
