=== PedroRuiz/interlingua/assets/xml/information.dtd
<!-- una DTD para carousel -->
<!ELEMENT information (lingua+) >
	<!ELEMENT lingua (namelingua,capite*,text*,final*)+ >
		<!ELEMENT namelingua	(#PCDATA)>
		<!ELEMENT capite		(#PCDATA)>
		
		<!ELEMENT text			(title*,paragrapho,image)>
            <!ELEMENT title 		(#PCDATA)>
            <!ELEMENT paragrapho	(#PCDATA)>
            <!ELEMENT image			(#PCDATA)>
			
		<!ELEMENT final			(#PCDATA)>

=== PedroRuiz/interlingua/assets/xml/information.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE information SYSTEM "information.dtd">

<information>
    
    <lingua>
        <namelingua>es</namelingua>
        <capite>¿Te interesa la comunicación internacional en Europa, Norteamérica, Sudamérica, Australia o grandes partes de África?</capite>
        <capite>¿Quieres aprender una lengua pero piensas que es demasiado difícil?</capite>
        <capite>¿Encuentras las lenguas interesantes en general?</capite>
        <capite>¡Toma en consideración interlingua, instrumento moderno de comunicación internacional!</capite>
        <text>
            <title>Paneuropea.</title>
            <paragrapho>Interlingua utiliza palabras extraídas de las siguientes lenguas: italiano, español/portugués, francés, inglés, alemán y ruso.</paragrapho>
            <image>https://interlingua.pedroruizhidalgo.es/assets/image/ia-europa.png</image>
        </text>
        <text>
            <title>Científica.</title>
            <paragrapho>Interlingua es el resultado de una gran cooperación entre lingüísticas y filólogos europeos y americanos. Ellos han extraído metódicamente el vocabulario internacional y común de las principales lenguas europeas.</paragrapho>
            <image>https://interlingua.pedroruizhidalgo.es/assets/image/ia-destillation.png</image>
        </text>
        <text>
            <title>Natural</title>
            <paragrapho>Ningún aspecto de interlingua es artificial o inventado. Cada característica se basa en al menos tres lenguas de origen europeo. Interlingua: ¡simplificación sin artificialidad!</paragrapho>
            <image>https://interlingua.pedroruizhidalgo.es/assets/image/ia-palmas.png</image>
        </text>
        <text>
            <title>Práctica</title>
            <paragrapho>Millones de personas comprenden interlingua a primera vista, especialmente los hablantes de lenguas neolatinas comprenden interlingua inmediatamente y casi sin esfuerzo. ¡Ideal para tus viages!</paragrapho>
            <image>https://interlingua.pedroruizhidalgo.es/assets/image/ia-conversation.png</image>
        </text>
        <text>
            <title>Fácil</title>
            <paragrapho>La gramática de interlingua es muy uniforme, y la pronunciación de las palabras sigue reglas estrictas y simples. Con interlingua, ninguna lista infinita de excepciones e irregularidades... ¡Aprender interlingua es agradable!</paragrapho>
            <image>https://interlingua.pedroruizhidalgo.es/assets/image/ia-facile.png</image>
        </text>
        <text>
            <title>Pedagógica</title>
            <paragrapho>Con interlingua, aprendes casi automáticamente muchas palabras extranjeras y cultas de tu lengua materna. Interlingua es la base ideal para tus posteriores estudios lingüísticos.</paragrapho>
            <image>https://interlingua.pedroruizhidalgo.es/assets/image/ia-libros.png</image>
        </text>
        <text>
            <title>Neutral</title>
            <paragrapho>Interlingua no es propiedad de una sola cultura o pueblo. Ningún hablante nativo tiene una ventaja injusta. Habla interlingua y pon fin a la discriminación lingüística.</paragrapho>
            <image>https://interlingua.pedroruizhidalgo.es/assets/image/ia-bandieras.png</image>
        </text>
        <text>
            <title>"Latín moderno"</title>
            <paragrapho>La mayoría de las palabras internacionales es de origen latín o griego. En interlingua, estas palabras internacionales toman formas prototipo o estandarizadas. El resultado es un “latín moderno” internacional y simplificado, elegante y práctico.</paragrapho>
            <image>https://interlingua.pedroruizhidalgo.es/assets/image/ia-ponte.png</image>
        </text>
        <text>
            <title>Divertida.</title>
            <paragrapho>Con interlingua encontrarás una creciente comunidad internacional compuesta de personas inteligentes y originales. Nuestras conferencias son experiencias inolvidables. ¡Ven y diviértete con nosotros!¡Serás siempre bienvenido!</paragrapho>
            <image>https://interlingua.pedroruizhidalgo.es/assets/image/ia-musica.png</image>
        </text>
        <final>INTERLINGUA es una lengua internacional que resultado de una gran cooperación de lingüistas de Europa y América. Las palabras de interlingua están basadas en las palabras internacionales del latino, griego y de otras lenguas en italiano, francés, español/portugués, inglés, alemán y ruso. La gramática de interlingua es simple y fácil. La pronunciación es regular y europea continental.</final>
    </lingua>
    
    <lingua>
        <namelingua>en</namelingua>
        <capite>Are you interested in international communication in Europe, North and South America, Australia, or large parts of Africa? Do you want to learn a language, but think it would be too difficult? Are you interested in languages in general? Consider/learn Interlingua, a modern tool for international communication!</capite>
        
        <text>
            <title>Pan-European.</title>
            <paragrapho>Interlingua uses words drawn from the following languages: Italian, Spanish/Portuguese, French, English, German, and Russian.</paragrapho>
            <image>https://interlingua.pedroruizhidalgo.es/assets/image/ia-europa.png</image>
        </text>
        <text>
            <title>Scientific.</title>
            <paragrapho>Interlingua is the result of an extensive cooperation of European and American linguists. They methodically extracted an international vocabulary common to the major languages of Europe.</paragrapho>
            <image>https://interlingua.pedroruizhidalgo.es/assets/image/ia-destillation.png</image>
        </text>
        <text>
            <title>Natural.</title>
            <paragrapho>No aspect of Interlingua is artificial or invented. Every characteristic is based on at least three languages of European origin. Interlingua: simplification without artificiality!</paragrapho>
            <image>https://interlingua.pedroruizhidalgo.es/assets/image/ia-palmas.png</image>
        </text>
        <text>
            <title>Practical</title>
            <paragrapho>Millions understand Interlingua "at first sight". Speakers of Romance languages especially understand Interlingua immediately and almost effortlessly. Ideal for traveling!</paragrapho>
            <image>https://interlingua.pedroruizhidalgo.es/assets/image/ia-conversation.png</image>
        </text>
        <text>
            <title>Easy</title>
            <paragrapho>The grammar of Interlingua is very uniform, and its pronunciation follows strict and simple rules. With Interlingua, there are no endless lists of exceptions and irregularities ... learning Interlingua is a pleasure!</paragrapho>
            <image>https://interlingua.pedroruizhidalgo.es/assets/image/ia-facile.png</image>
        </text>
        <text>
            <title>Educational</title>
            <paragrapho>With Interlingua, you learn almost automatically many "foreign" or "learned" words in your own native language. Interlingua is an ideal basis for further study of languages.</paragrapho>
            <image>https://interlingua.pedroruizhidalgo.es/assets/image/ia-libros.png</image>
        </text>
        <text>
            <title>Neutral</title>
            <paragrapho>Interlingua isn't the property of a single culture or people. No native speaker has an unfair advantage. Speak Interlingua and put an end to linguistic discrimination.</paragrapho>
            <image>https://interlingua.pedroruizhidalgo.es/assets/image/ia-bandieras.png</image>
        </text>
        <text>
            <title>"Modern Latin"</title>
            <paragrapho>Most international words are of Latin or Greek origin. In Interlingua, these international words take prototypical and standardized form. The result is a "modern Latin", international and simplified, elegant and practical.</paragrapho>
            <image>https://interlingua.pedroruizhidalgo.es/assets/image/ia-ponte.png</image>
        </text>
        <text>
            <title>Fun.</title>
            <paragrapho>With Interlingua you encounter a growing community full of intelligent and original people. Our conferences are unforgettable experiences. Come and have fun with us! We welcome you!</paragrapho>
            <image>https://interlingua.pedroruizhidalgo.es/assets/image/ia-musica.png</image>
        </text>
        <final>INTERLINGUA is an international language that was the result of an extensive cooperation of linguists from Europe and America. The words of Interlingua are based on international words that come from Latin, Greek and other languages, and exist in Italian, French, Spanish/Portuguese, English, German, and Russian. The grammar of Interlingua is simple and easy. The pronounciation is regular and continental European.

For more information, please contact:
British Interlingua Society
Brian C. Sexton
Flat 14 Ventnor Court
Wostenholm Road
Sheffield S7 1LB
United Kingdom
Tel: +44-114-2582931 </final>
    </lingua>
    
    <lingua>
        <namelingua>ar</namelingua>
        <capite>هل تهمكم الاتصالات الدولية في أوربا , اميركا الشمالية و الجنوبية , أوستراليا , و أجزاء كبيرة من أفريقيا ؟ تريدون تعلم إحدى اللغات و لكنكم تعتقدون أنها صعبة جدا ؟ تجدون , بشكل عام , أن اللغات الأجنبية مثيرة للإهتمام ؟ ما عليكم إلا أن تأخذوا بعين الاعتبار إنترلينغوا , الطريقة الحديثة للاتصالات الدولية .</capite>
        <text>
            <title>عابرة لأوربا.</title>
            <paragrapho>إنترلينغوا تستعمل كلمات مستخرجة من اللغة الإيطالية , الإسبانية , البرتغالية , الفرنسية , الانكليزية , الألمانية و الروسية . </paragrapho>
            <image>https://interlingua.pedroruizhidalgo.es/assets/image/ia-europa.png</image>
        </text>
        <text>
            <title>علمية.</title>
